# Generated by Django 2.0.6 on 2018-07-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='marked',
        ),
    ]
